apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: truyencv-db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: truyencv-db
    tier: postgres
  ports:
    - port: 5432
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyencv-db
  labels:
    app: truyencv-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: truyencv-db
  strategy:
    type: Recreate
  template:
    metadata:
      name: truyencv-db
      labels:
        app: truyencv-db
        tier: postgres
    spec:
      containers:
        - name: truyencv-db
          image: postgres:16.3-alpine
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: name
                  name: postgres-db-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: postgres-db-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-db-secret
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim


